export class City {
  public name: string;

  public code: number;

  constructor(name: string, cityCode: string) {
    this.name = name;
    this.code = parseInt(cityCode, 10);
  }
}

export default [
  new City('Adana', '01'),
  new City('Adıyaman', '02'),
  new City('Afyon', '03'),
  new City('Ağrı', '04'),
  new City('Amasya', '05'),
  new City('Ankara', '06'),
  new City('Antalya', '07'),
  new City('Artvin', '08'),
  new City('Aydın', '09'),
  new City('Balıkesir', '10'),
  new City('Bilecik', '11'),
  new City('Bingöl', '12'),
  new City('Bitlis', '13'),
  new City('Bolu', '14'),
  new City('Burdur', '15'),
  new City('Bursa', '16'),
  new City('Çanakkale', '17'),
  new City('Çankırı', '18'),
  new City('Çorum', '19'),
  new City('Denizli', '20'),
  new City('Diyarbakır', '21'),
  new City('Edirne', '22'),
  new City('Elazığ', '23'),
  new City('Erzincan', '24'),
  new City('Erzurum', '25'),
  new City('Eskişehir', '26'),
  new City('Gaziantep', '27'),
  new City('Giresun', '28'),
  new City('Gümüşhane', '29'),
  new City('Hakkari', '30'),
  new City('Hatay', '31'),
  new City('Isparta', '32'),
  new City('İçel', '33'),
  new City('İstanbul', '34'),
  new City('İzmir', '35'),
  new City('Kars', '36'),
  new City('Kastamonu', '37'),
  new City('Kayseri', '38'),
  new City('Kırklareli', '39'),
  new City('Kırşehir', '40'),
  new City('Kocaeli', '41'),
  new City('Konya', '42'),
  new City('Kütahya', '43'),
  new City('Malatya', '44'),
  new City('Manisa', '45'),
  new City('Kahramanmaraş', '46'),
  new City('Mardin', '47'),
  new City('Muğla', '48'),
  new City('Muş', '49'),
  new City('Nevşehir', '50'),
  new City('Niğde', '51'),
  new City('Ordu', '52'),
  new City('Rize', '53'),
  new City('Sakarya', '54'),
  new City('Samsun', '55'),
  new City('Siirt', '56'),
  new City('Sinop', '57'),
  new City('Sivas', '58'),
  new City('Tekirdağ', '59'),
  new City('Tokat', '60'),
  new City('Trabzon', '61'),
  new City('Tunceli', '62'),
  new City('Şanlıurfa', '63'),
  new City('Uşak', '64'),
  new City('Van', '65'),
  new City('Yozgat', '66'),
  new City('Zonguldak', '67'),
  new City('Aksaray', '68'),
  new City('Bayburt', '69'),
  new City('Karaman', '70'),
  new City('Kırıkkale', '71'),
  new City('Batman', '72'),
  new City('Şırnak', '73'),
  new City('Bartın', '74'),
  new City('Ardahan', '75'),
  new City('Iğdır', '76'),
  new City('Yalova', '77'),
  new City('Karabük', '78'),
  new City('Kilis', '79'),
  new City('Osmaniye', '80'),
  new City('Düzce', '81'),
];
